---
- name: Тест отчёта Telegram
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Отправка тестового отчёта Telegram
      ansible.builtin.include_role: { name: telegram }
      vars:
        telegram_message: |-
          <b>Ротация CDN выполнена</b>
          нода: <code>node_ch1</code> (45.95.232.74)
          origin: <code>arvi42.zorelium.site</code>
          фронты: <code>{"vk":"pulse-orbi56.zorelium.site","yandex":"edge-demo.example"}</code>
          инбаунд: <code>CDN_P01</code>  path: <code>/api/library/sync</code>
          ресурсы: <code>{"vk":"5467859","yandex":"bc123"}</code>
          плеч в балансере: 3
